### ISSUE TITLE
作者您好，我是个初学者，在学习您的代码

### ISSUE THREAD

**Issue by totolerater** [bochuanwu/Agricultural-Disease-Classification#7]
代码中的weights.hdf5您是怎么得到的呢？可不可以分享一下？真的万分感谢！！！！

**Comment by bochuanwu** [comment]
> 代码中的weights.hdf5您是怎么得到的呢？可不可以分享一下？真的万分感谢！！！！

训练完就应该会得到weights权重文件， 这个比赛太久远了，我的权重文件不太好找了

**Comment by bochuanwu** [comment]
这个比赛代码已经很老了  而且基于keras  建议学习pytorch或者tensorflow。

**Comment by totolerater** [comment]
嗯，已经解决了，还在继续学tensorflow，谢谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "bochuan wu"<notifications@github.com&gt;; 
发送时间: 2020年5月12日(星期二) 中午11:09
收件人: "bochuanwu/Agricultural-Disease-Classification"<Agricultural-Disease-Classification@noreply.github.com&gt;; 
抄送: "1041489946"<1041489946@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bochuanwu/Agricultural-Disease-Classification] 作者您好，我是个初学者，在学习您的代码 (#7)





 
这个比赛代码已经很老了  而且基于keras  建议学习pytorch或者tensorflow。
